### PR TITLE
Example files which run with the MAX485 TTL Module and the purple Soyo

### PR DESCRIPTION
**Pull request by IAmWebSA**
For ESP32 and ESP8266 Wemos D1 Mini Pro GTN1000 and limit to 600W to fullfill law in case to much power would be pushed into grid.

### CODE REVIEW

**Comment by syssi** [comment]
Thanks for your contribution! Could you try to summarize the differences to the standard example as comment at the top of the YAMLs? IMO these details should be mentioned/specified:

1. This configuration is for silent Soyosource inverters which doesn't respond to status requests. Therefore no status informations like the operation mode are available and cannot be monitored. The monitoring of the operation mode is disabled.
2. The instantaneous power is extracted from a JSON response periodically retrieved via HTTP from a Shelly XYZ running firmware ABC.
3. The maximum power output and select entities are limited to 600W in order to not violate the regulations in germany.

**Comment by IAmWebSA** [comment]
Added comments as suggested

**Comment by syssi** [comment]
I would like to change same additional details. I'm allowed to change the examples at your main branch? I don't want to destroy your production setup/configuration.

**Comment by IAmWebSA** [comment]
Sure you are allowed, feel free to adapt the changes.

**Pull request merged**
